### PR TITLE
Added support for constant

### PR DESCRIPTION
**Pull request by dovidkopel**

### CODE REVIEW

**Comment by dovidkopel** [comment]
It is useful because new scripts may come into play that want to declare a constant. For them its just the beginning of the application. I had to make the change to allow for the ui-boostrap code to work in a module I was building that is loaded dynamically.

**Comment by laurelnaiad** [comment]
RIght, makes sense. I'm so pleased that Angular 2.0 will do away with the distinction between config and run time. What a headache that is (and of course that is also why couch-potato exists). :)

**Comment by dovidkopel** [comment]
It is necessary, excited for 2.0 as well.

**Comment by laurelnaiad** [comment]
Merged as 00440aee7fa7be12d5d4db1593aacbc49f456f76

Thanks, Dovid.

**Comment by dovidkopel** [comment]
No problem, thanks for the script!

**Comment by laurelnaiad** [comment]
I forgot to up the version number uniformly, but it should be straightened out int the last commit. Make sure you force 0.2.1 or higher (e.g. ~0.2.1)

**Pull request closed without merging**
